version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: conta
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
