version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: feedback-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: feedbackdb
      POSTGRES_USER: feed
      POSTGRES_PASSWORD: 123
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
